### PR TITLE
Added functionality to auto download photos

### LINKED ISSUE #24: Save all Photos or # no. of photos from someones Whatsapp chat to Computer

### PR DESCRIPTION
**Pull request by Contrevien**
The contact should have some history of photos or the script will fail.

@shauryauppal Please review
Probably closes #24

### CODE REVIEW

**Comment by shauryauppal** [comment]
@Contrevien will check it tomorrow. Also recheck line number 93.

**Comment by Contrevien** [comment]
@shauryauppal It is function's Dogtag which explains what the function does, dunno why it's popping error because the script is working fine

**Comment by shauryauppal** [comment]
Why is this an issue?
This message is emitted when a string statement is found, but which doesn't have any semantic purpose other than documenting the surrounding code. It can also be a potential problem, if the original intent was to write a docstring.

def foo(self):
    """This is a docstring."""
    """This is not and it's superfluous, it could be rewritten as comments."""

**Comment by shauryauppal** [comment]
Line 93

**Comment by shauryauppal** [comment]
Sorry but I still have not got time to run from your repo will try to run tomorrow and will merge. I am sure you have done this nicely. For the error can't we add a try catch or something so that is the image is not visible it skips that image or something. The script should not stop. @Contrevien

**Comment by ShauryaUppal-1Mg** [comment]
Problem 1: All Images cannot be downloaded using this method.

Problem 2: Whatsapp has changes all the class names and hence this has to changes.

Xpath would have helped here the best.

**Comment by shauryauppal** [comment]
All the class names are changed by WhatsApp. Download no more works in hardcoded class names. 

Adding Xpaths to class names would have been better.

**Pull request closed without merging**
