### PR TITLE
Made a few code edits and optimization

### PR DESCRIPTION
**Pull request by Shakthi-Dhar**
Added full XPATH for send_attachment function and removed unnecessary sleep calls.

### CODE REVIEW

**Comment by shauryauppal** [comment]
What are .idea files? Your PR has 7 file changes. Can you check/explain change in .idea?

**Comment by shauryauppal** [comment]
Mate sleep was on purpose Whatsapp catches it as a bot too soon then. Sleep is to act like a human. Don't remove those.

**Comment by shauryauppal** [comment]
Also full xpath or the one already there does not change any functionality.

**Comment by Shakthi-Dhar** [comment]
My bad the .idea files were generated on pycharm ide

**Pull request closed without merging**
